version: "2.1"

services:

  mongo:
    restart: unless-stopped
    image: healthcheck/mongo:latest
    ports: ["27017:27017"]
    volumes: ["mongo-data:/data/db"]
    networks: [backing-services]

  mongo-express:
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_healthy
    image: mongo-express:0.42.2
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    ports: ["8081:8081"]
    volumes: ["mongo-express-data:/node_modules/mongo-express"]
    networks: [backing-services]

volumes:
  mongo-data: {}
  mongo-express-data: {}

networks:
  backing-services:
    driver: bridge
